/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author PC
 */
public class AddClass extends javax.swing.JFrame {

        /**
         * Creates new form AddClass
         */
        public AddClass() {
                initComponents();
                loadClassData();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                class_tf_classname = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                class_tf_classcode = new javax.swing.JTextField();
                class_btn_addclass = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                class_btn_delete = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                class_table = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(153, 153, 255));

                jPanel2.setBackground(new java.awt.Color(102, 102, 255));

                jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Add Class");

                jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel3.setText("Class Name:");

                class_tf_classname.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                class_tf_classnameActionPerformed(evt);
                        }
                });

                jLabel5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel5.setText("Class Code:");

                class_btn_addclass.setBackground(new java.awt.Color(204, 255, 255));
                class_btn_addclass.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                class_btn_addclass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (1).png"))); // NOI18N
                class_btn_addclass.setText("Add Class");
                class_btn_addclass.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                class_btn_addclassActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(class_btn_addclass,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                245,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(class_tf_classname,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(class_tf_classcode,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(class_tf_classname,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(class_tf_classcode,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(99, 99, 99)
                                                                .addComponent(class_btn_addclass,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(130, Short.MAX_VALUE)));

                jLabel2.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Class List");

                class_btn_delete.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                class_btn_delete.setText("Delete Map");
                class_btn_delete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                class_btn_deleteActionPerformed(evt);
                        }
                });

                class_table.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Class Name", "Class Code"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(class_table);
                if (class_table.getColumnModel().getColumnCount() > 0) {
                        class_table.getColumnModel().getColumn(0).setResizable(false);
                        class_table.getColumnModel().getColumn(1).setResizable(false);
                }

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(class_btn_delete))
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                599,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                47,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(3, 3, 3)
                                                                .addComponent(class_btn_delete)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                0,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        private void class_tf_classnameActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void class_btn_addclassActionPerformed(java.awt.event.ActionEvent evt) {
                String class_name = class_tf_classname.getText();
                String class_code = class_tf_classcode.getText();

                if (class_name.isEmpty() || class_code.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Please fill all the fields", "Try Again",
                                        JOptionPane.ERROR_MESSAGE);
                } else {
                        try {
                                // Database Connection
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                                "root", "aswin@2004");
                                String sql = "INSERT INTO class (class_name, class_code) VALUES (?, ?)";
                                PreparedStatement pst = con.prepareStatement(sql);
                                pst.setString(1, class_name);
                                pst.setString(2, class_code);

                                int rowsInserted = pst.executeUpdate();
                                if (rowsInserted > 0) {
                                        JOptionPane.showMessageDialog(this, "Class added successfully!");

                                        // Adding to table model
                                        DefaultTableModel model = (DefaultTableModel) class_table.getModel();
                                        model.addRow(new Object[] { class_name, class_code });
                                }

                                // Close resources
                                pst.close();
                                con.close();
                        } catch (SQLException e) {
                                JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                }

                class_tf_classname.setText("");
                class_tf_classcode.setText("");
        }

        private void class_btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = class_table.getSelectedRow(); // Get selected row index

                if (selectedRow == -1) {
                        JOptionPane.showMessageDialog(this, "Please select a class to delete!", "Warning",
                                        JOptionPane.WARNING_MESSAGE);
                        return;
                }

                DefaultTableModel model = (DefaultTableModel) class_table.getModel();
                String classCode = model.getValueAt(selectedRow, 1).toString(); // Assuming class_code is in column
                                                                                // index 1

                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this class?",
                                "Confirm Deletion", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                        try {
                                // Replace with your actual database connection details
                                Connection con = DriverManager.getConnection(
                                                "jdbc:mysql://localhost:3306/timesync", "root", "aswin@2004");
                                String query = "DELETE FROM class WHERE class_code = ?"; // Modify as needed
                                PreparedStatement pstmt = con.prepareStatement(query);
                                pstmt.setString(1, classCode);

                                int rowsAffected = pstmt.executeUpdate();
                                pstmt.close();
                                con.close();

                                if (rowsAffected > 0) {
                                        model.removeRow(selectedRow); // Remove row from table
                                        JOptionPane.showMessageDialog(this, "Class deleted successfully!", "Success",
                                                        JOptionPane.INFORMATION_MESSAGE);
                                } else {
                                        JOptionPane.showMessageDialog(this, "Class not found in database!", "Error",
                                                        JOptionPane.ERROR_MESSAGE);
                                }

                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, "Error deleting class: " + e.getMessage(), "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                }
        }

        private void loadClassData() {
                DefaultTableModel model = (DefaultTableModel) class_table.getModel();
                model.setRowCount(0); // Clear existing data

                try {
                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "SELECT class_name, class_code FROM class"; // Modify according to your table
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String className = rs.getString("class_name");
                                String classCode = rs.getString("class_code");
                                model.addRow(new Object[] { className, classCode });
                        }

                        rs.close();
                        stmt.close();
                        con.close();
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        private void loadClass() {
                try {
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync", "root",
                                        "aswin@2004");
                        Statement stm = con.createStatement();
                        String q = "select * from class;";
                        // int i = stm.executeUpdate(q);
                        // qry = "select * from students order by roll_No asc;";
                        ResultSet res = stm.executeQuery(q);
                        DefaultTableModel model = (DefaultTableModel) class_table.getModel();

                        while (res.next()) {
                                System.out.println(res.getInt(1) + "  " + res.getString(2));
                                model.addRow(new Object[] { res.getString(1), res.getString(2) });
                        }
                        stm.close();
                        con.close();
                } catch (Exception e) {
                        System.out.println(e);
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */

                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AddClass().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton class_btn_addclass;
        private javax.swing.JButton class_btn_delete;
        private static javax.swing.JTable class_table;
        private javax.swing.JTextField class_tf_classcode;
        private javax.swing.JTextField class_tf_classname;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration
}
