/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class AddFaculty extends javax.swing.JFrame {

        /**
         * Creates new form AddFaculty
         */
        public AddFaculty() {
                initComponents();
                LoadFacultyTable();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                faculty_tf_facultyname = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                faculty_tf_facultycode = new javax.swing.JTextField();
                faculty_addfaculty = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                faculty_table = new javax.swing.JTable();
                jLabel4 = new javax.swing.JLabel();
                faculty_btn_deletefaculty = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(204, 255, 255));

                jPanel2.setBackground(new java.awt.Color(204, 204, 255));

                jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Add Faculty");

                jLabel2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel2.setText("Faculty Name:");

                faculty_tf_facultyname.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                faculty_tf_facultynameActionPerformed(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel3.setText("Faculty Code");

                faculty_addfaculty.setBackground(new java.awt.Color(0, 204, 204));
                faculty_addfaculty.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                faculty_addfaculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (1).png"))); // NOI18N
                faculty_addfaculty.setText("Add Faculty");
                faculty_addfaculty.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                faculty_addfacultyActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(faculty_tf_facultycode)
                                                                                .addComponent(faculty_addfaculty,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                295, Short.MAX_VALUE)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(faculty_tf_facultyname)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                33,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(faculty_tf_facultyname,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(59, 59, 59)
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(faculty_tf_facultycode,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(faculty_addfaculty,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                55,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(47, 47, 47)));

                faculty_table.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                faculty_table.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Faculty Name", "Faculty Code"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(faculty_table);

                jLabel4.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("Faculty List");

                faculty_btn_deletefaculty.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                faculty_btn_deletefaculty.setText("Delete Faculty");
                faculty_btn_deletefaculty.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                faculty_btn_deletefacultyActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                610, Short.MAX_VALUE)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(faculty_btn_deletefaculty)))
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(faculty_btn_deletefaculty)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                412,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        private void faculty_addfacultyActionPerformed(java.awt.event.ActionEvent evt) {
                String faculty_name = faculty_tf_facultyname.getText();
                String faculty_code = faculty_tf_facultycode.getText();

                if (faculty_name.isEmpty() || faculty_code.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Please fill all the fields", "Try Again",
                                        JOptionPane.ERROR_MESSAGE);
                } else {
                        try {
                                // Database Connection
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                                "root", "aswin@2004");
                                String sql = "INSERT INTO faculty (faculty_name, faculty_code) VALUES (?, ?)";
                                PreparedStatement pst = con.prepareStatement(sql);
                                pst.setString(1, faculty_name);
                                pst.setString(2, faculty_code);

                                int rowsInserted = pst.executeUpdate();
                                if (rowsInserted > 0) {
                                        JOptionPane.showMessageDialog(this, "Class added successfully!");

                                        // Adding to table model
                                        DefaultTableModel model = (DefaultTableModel) faculty_table.getModel();
                                        model.addRow(new Object[] { faculty_name, faculty_code });
                                }

                                // Close resources
                                pst.close();
                                con.close();
                        } catch (SQLException e) {
                                JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                }

                faculty_tf_facultyname.setText("");
                faculty_tf_facultycode.setText("");
        }

        private void faculty_tf_facultynameActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void faculty_btn_deletefacultyActionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = faculty_table.getSelectedRow(); // Get selected row index

                if (selectedRow == -1) {
                        JOptionPane.showMessageDialog(this, "Please select a class to delete!", "Warning",
                                        JOptionPane.WARNING_MESSAGE);
                        return;
                }

                DefaultTableModel model = (DefaultTableModel) faculty_table.getModel();
                String classCode = model.getValueAt(selectedRow, 1).toString(); // Assuming class_code is in column
                                                                                // index 1

                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this class?",
                                "Confirm Deletion", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                        try {
                                // Replace with your actual database connection details
                                Connection con = DriverManager.getConnection(
                                                "jdbc:mysql://localhost:3306/timesync", "root", "aswin@2004");
                                String query = "DELETE FROM faculty WHERE faculty_code = ?"; // Modify as needed
                                PreparedStatement pstmt = con.prepareStatement(query);
                                pstmt.setString(1, classCode);

                                int rowsAffected = pstmt.executeUpdate();
                                pstmt.close();
                                con.close();

                                if (rowsAffected > 0) {
                                        model.removeRow(selectedRow); // Remove row from table
                                        JOptionPane.showMessageDialog(this, "Class deleted successfully!", "Success",
                                                        JOptionPane.INFORMATION_MESSAGE);
                                } else {
                                        JOptionPane.showMessageDialog(this, "Class not found in database!", "Error",
                                                        JOptionPane.ERROR_MESSAGE);
                                }

                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, "Error deleting class: " + e.getMessage(), "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                }
        }

        private void LoadFacultyTable() {
                DefaultTableModel model = (DefaultTableModel) faculty_table.getModel();
                model.setRowCount(0); // Clear existing data

                try {
                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "SELECT faculty_name, faculty_code FROM faculty"; // Modify according to your
                                                                                         // table
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String className = rs.getString("faculty_name");
                                String classCode = rs.getString("faculty_code");
                                model.addRow(new Object[] { className, classCode });
                        }

                        rs.close();
                        stmt.close();
                        con.close();
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(AddFaculty.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(AddFaculty.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(AddFaculty.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(AddFaculty.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new AddFaculty().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton faculty_addfaculty;
        private javax.swing.JButton faculty_btn_deletefaculty;
        private javax.swing.JTable faculty_table;
        private javax.swing.JTextField faculty_tf_facultycode;
        private javax.swing.JTextField faculty_tf_facultyname;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        // End of variables declaration
}
