/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class GenerateScreen extends javax.swing.JFrame {

        /**
         * Creates new form Generated_Schedule
         */
        public GenerateScreen() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                generate_btn_class = new javax.swing.JButton();
                generate_cmp_class = new javax.swing.JComboBox<>();
                jPanel5 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                generate_btn_faculty = new javax.swing.JButton();
                generate_cmp_faculty = new javax.swing.JComboBox<>();
                jLabel1 = new javax.swing.JLabel();
                generate_heading = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                generate_table = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 153));

                jPanel2.setBackground(new java.awt.Color(204, 204, 204));

                jPanel3.setBackground(new java.awt.Color(102, 102, 102));
                jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                jPanel4.setBackground(new java.awt.Color(102, 102, 102));
                jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

                jLabel2.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Class:");

                generate_btn_class.setBackground(new java.awt.Color(255, 255, 204));
                generate_btn_class.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
                generate_btn_class.setText("Show Class Shedule");
                generate_btn_class.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                generate_btn_classActionPerformed(evt);
                        }
                });

                try {
                        ArrayList<String> class_time_table_list = new ArrayList<>(); // Use ArrayList instead of an
                                                                                     // array

                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "select distinct(name) from class_time_table";
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String className = rs.getString("name");
                                class_time_table_list.add(className); // Add subjects to the list
                        }

                        rs.close();
                        stmt.close();
                        con.close();

                        // Update JComboBox dynamically with retrieved subjects
                        generate_cmp_class.setModel(
                                        new DefaultComboBoxModel<>(class_time_table_list.toArray(new String[0])));

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(generate_btn_class,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(generate_cmp_class, 0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(generate_cmp_class,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(generate_btn_class,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(26, Short.MAX_VALUE)));

                jPanel5.setBackground(new java.awt.Color(102, 102, 102));
                jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

                jLabel4.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("Faculty:");

                generate_btn_faculty.setBackground(new java.awt.Color(255, 255, 204));
                generate_btn_faculty.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
                generate_btn_faculty.setText("Show Fcaulty Schedule");
                generate_btn_faculty.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                generate_btn_facultyActionPerformed(evt);
                        }
                });

                try {
                        ArrayList<String> faculty_time_table_list = new ArrayList<>(); // Use ArrayList instead of an
                                                                                       // array

                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "select distinct(name) from faculty_time_table";
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String className = rs.getString("name");
                                faculty_time_table_list.add(className); // Add subjects to the list
                        }

                        rs.close();
                        stmt.close();
                        con.close();

                        // Update JComboBox dynamically with retrieved subjects
                        generate_cmp_faculty.setModel(
                                        new DefaultComboBoxModel<>(faculty_time_table_list.toArray(new String[0])));

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(generate_btn_faculty,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(generate_cmp_faculty, 0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(generate_cmp_faculty,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                31,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(generate_btn_faculty,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(26, Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jPanel4,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel5,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(42, 42, 42)
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(212, 212, 212)));

                jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
                jLabel1.setText("Select Class Or Fcaulty");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jPanel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                generate_heading.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
                generate_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                generate_heading.setText("Time Sync");

                generate_table.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Period 1", "Period 2", "Period 3", "Period 4", "Period 5", "Period 6",
                                                "Period 7", "Period 8"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class,
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(generate_table);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(generate_heading,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                623,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 9, Short.MAX_VALUE)))
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addComponent(generate_heading,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(35, 35, 35)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                356,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482,
                                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        private void generate_btn_classActionPerformed(java.awt.event.ActionEvent evt) {
                load_class_data();
        }

        // TODO add your handling code here:
        private void load_class_data() {
                DefaultTableModel model = (DefaultTableModel) generate_table.getModel();
                model.setRowCount(0); // Clear existing data
                String class_selected = String.valueOf(generate_cmp_class.getSelectedItem());
                generate_heading.setText("Selected Shedule For:  " + class_selected);
                try {
                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "SELECT * FROM class_time_table WHERE name = \"" + class_selected + "\"";
                        // according to
                        // your table
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String period1 = rs.getString("period1");
                                String period2 = rs.getString("period2");
                                String period3 = rs.getString("period3");
                                String period4 = rs.getString("period4");
                                String period5 = rs.getString("period5");
                                String period6 = rs.getString("period6");
                                String period7 = rs.getString("period7");
                                String period8 = rs.getString("period8");
                                model.addRow(new Object[] { period1, period2, period3, period4, period5, period6,
                                                period7, period8 });
                        }

                        rs.close();
                        stmt.close();
                        con.close();
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        private void load_faculty_data() {
                DefaultTableModel model = (DefaultTableModel) generate_table.getModel();
                model.setRowCount(0); // Clear existing data
                String faculty_selected = String.valueOf(generate_cmp_faculty.getSelectedItem());
                generate_heading.setText("Selected Shedule For:  " + faculty_selected);
                try {
                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "SELECT * FROM faculty_time_table WHERE name = \"" + faculty_selected + "\"";
                        // according to
                        // your table
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String period1 = rs.getString("period1");
                                String period2 = rs.getString("period2");
                                String period3 = rs.getString("period3");
                                String period4 = rs.getString("period4");
                                String period5 = rs.getString("period5");
                                String period6 = rs.getString("period6");
                                String period7 = rs.getString("period7");
                                String period8 = rs.getString("period8");
                                model.addRow(new Object[] { period1, period2, period3, period4, period5, period6,
                                                period7, period8 });
                        }

                        rs.close();
                        stmt.close();
                        con.close();
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        private void generate_btn_facultyActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                load_faculty_data();
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(GenerateScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(GenerateScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(GenerateScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(GenerateScreen.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new GenerateScreen().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton generate_btn_class;
        private javax.swing.JButton generate_btn_faculty;
        private javax.swing.JComboBox<String> generate_cmp_class;
        private javax.swing.JComboBox<String> generate_cmp_faculty;
        private javax.swing.JLabel generate_heading;
        private javax.swing.JTable generate_table;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JScrollPane jScrollPane1;
        public String selected_variable_name = "";
        // End of variables declaration
}
