/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class MapClasses extends javax.swing.JFrame {

        /**
         * Creates new form MapClasses
         */
        public MapClasses() {
                initComponents();
                loadMapData();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                map_btn_map = new javax.swing.JButton();
                map_cmp_class = new javax.swing.JComboBox<>();
                jLabel6 = new javax.swing.JLabel();
                map_cmp_faculty = new javax.swing.JComboBox<>();
                map_cmp_subject = new javax.swing.JComboBox<>();
                jLabel7 = new javax.swing.JLabel();
                map_tf_hours = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                map_btn_delete = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                map_table = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(153, 153, 255));

                jPanel2.setBackground(new java.awt.Color(102, 102, 255));

                jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Map Class");

                jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel3.setText("Select Class:");

                jLabel5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel5.setText("Select Subject:");

                map_btn_map.setBackground(new java.awt.Color(204, 255, 255));
                map_btn_map.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                map_btn_map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (1).png"))); // NOI18N
                map_btn_map.setText("Map");
                map_btn_map.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                map_btn_mapActionPerformed(evt);
                        }
                });

                try {
                        ArrayList<String> subjectList = new ArrayList<>(); // Use ArrayList instead of an array

                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "SELECT class_name, class_code FROM class";
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String className = rs.getString("class_code");
                                subjectList.add(className); // Add subjects to the list
                        }

                        rs.close();
                        stmt.close();
                        con.close();

                        // Update JComboBox dynamically with retrieved subjects
                        map_cmp_class.setModel(new DefaultComboBoxModel<>(subjectList.toArray(new String[0])));

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }

                map_cmp_class.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                map_cmp_classActionPerformed(evt);
                        }
                });

                jLabel6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel6.setText("Select Faculty:");

                try {
                        ArrayList<String> subjectList = new ArrayList<>(); // Use ArrayList instead of an array

                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "SELECT faculty_name, faculty_code FROM faculty";
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String className = rs.getString("faculty_name");
                                subjectList.add(className); // Add subjects to the list
                        }

                        rs.close();
                        stmt.close();
                        con.close();

                        // Update JComboBox dynamically with retrieved subjects
                        map_cmp_faculty.setModel(new DefaultComboBoxModel<>(subjectList.toArray(new String[0])));

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }

                map_cmp_faculty.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                map_cmp_facultyActionPerformed(evt);
                        }
                });

                try {
                        ArrayList<String> subjectList = new ArrayList<>(); // Use ArrayList instead of an array

                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "SELECT subject_name, subject_code FROM subject";
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String className = rs.getString("subject_name");
                                subjectList.add(className); // Add subjects to the list
                        }

                        rs.close();
                        stmt.close();
                        con.close();

                        // Update JComboBox dynamically with retrieved subjects
                        map_cmp_subject.setModel(new DefaultComboBoxModel<>(subjectList.toArray(new String[0])));

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }

                jLabel7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel7.setText("Hours for Subject:");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(map_btn_map, javax.swing.GroupLayout.DEFAULT_SIZE, 257,
                                                                Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(map_tf_hours)
                                                                                .addComponent(map_cmp_class, 0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                245, Short.MAX_VALUE)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(map_cmp_subject,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel6,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(map_cmp_faculty,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel7,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(map_cmp_class,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                34,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(map_cmp_subject,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                34,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(map_cmp_faculty,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                34,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(map_tf_hours,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(map_btn_map,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(32, 32, 32)));

                jLabel2.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("Mapped List");

                map_btn_delete.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                map_btn_delete.setText("Delete Map");
                map_btn_delete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                map_btn_deleteActionPerformed(evt);
                        }
                });

                map_table.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Class", "Subject", "Faculty", "Hours"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.String.class, java.lang.String.class,
                                        java.lang.String.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(map_table);
                if (map_table.getColumnModel().getColumnCount() > 0) {
                        map_table.getColumnModel().getColumn(0).setResizable(false);
                        map_table.getColumnModel().getColumn(1).setResizable(false);
                }

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(map_btn_delete))
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                599, Short.MAX_VALUE)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                47,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(3, 3, 3)
                                                                .addComponent(map_btn_delete)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                483, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        private void map_cmp_subjectActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void map_cmp_classActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void map_btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = map_table.getSelectedRow();

                if (selectedRow == -1) {
                        JOptionPane.showMessageDialog(this, "Please select a Map to delete!", "Warning",
                                        JOptionPane.WARNING_MESSAGE);
                        return;
                }

                DefaultTableModel model = (DefaultTableModel) map_table.getModel();
                String classname = model.getValueAt(selectedRow, 0).toString().trim();
                String subject = model.getValueAt(selectedRow, 1).toString().trim();
                String faculty = model.getValueAt(selectedRow, 2).toString().trim();
                String hours = model.getValueAt(selectedRow, 3).toString().trim();

                System.out.println("Deleting: ");
                System.out.println("Class: " + classname);
                System.out.println("Subject: " + subject);
                System.out.println("Faculty: " + faculty);
                System.out.println("Hours: " + hours);

                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this subject?",
                                "Confirm Deletion", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                        try {
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                                "root", "aswin@2004");

                                String query = "DELETE FROM map WHERE class = ? and subject = ? and faculty = ? and hours = ?";
                                PreparedStatement pstmt = con.prepareStatement(query);
                                pstmt.setString(1, classname);
                                pstmt.setString(2, subject);
                                pstmt.setString(3, faculty);
                                pstmt.setString(4, hours);

                                int rowsAffected = pstmt.executeUpdate();
                                pstmt.close();
                                con.close();

                                if (rowsAffected > 0) {
                                        model.removeRow(selectedRow); // Remove from table
                                        JOptionPane.showMessageDialog(this, "Map deleted successfully!", "Success",
                                                        JOptionPane.INFORMATION_MESSAGE);
                                } else {
                                        JOptionPane.showMessageDialog(this, "Map not found in database!", "Error",
                                                        JOptionPane.ERROR_MESSAGE);
                                }
                        } catch (Exception e) {
                                e.printStackTrace();
                                JOptionPane.showMessageDialog(this, "Error deleting class: " + e.getMessage(), "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                }
        }

        private void map_btn_mapActionPerformed(java.awt.event.ActionEvent evt) {
                String class_name = (String) map_cmp_class.getSelectedItem();
                String subject_name = (String) map_cmp_subject.getSelectedItem();
                String faculty_name = (String) map_cmp_faculty.getSelectedItem();
                String hours = (String) map_tf_hours.getText();

                try {
                        // Database Connection
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        String sql = "INSERT INTO map (class,subject,faculty,hours) VALUES (?, ?,?,?)";
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, class_name);
                        pst.setString(2, subject_name);
                        pst.setString(3, faculty_name);
                        pst.setString(4, hours);

                        int rowsInserted = pst.executeUpdate();
                        if (rowsInserted > 0) {
                                JOptionPane.showMessageDialog(this, "Class added successfully!");

                                // Adding to table model
                                DefaultTableModel model = (DefaultTableModel) map_table.getModel();
                                model.addRow(new Object[] { class_name, subject_name, faculty_name, hours });
                        }

                        // Close resources
                        pst.close();
                        con.close();
                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        private void map_cmp_facultyActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
        }

        private void loadMapData() {
                DefaultTableModel model = (DefaultTableModel) map_table.getModel();
                model.setRowCount(0); // Clear existing data

                try {
                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "SELECT * FROM map"; // Modify according to your table
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String class_name = rs.getString("class");
                                String subject = rs.getString("subject");
                                String faculty = rs.getString("faculty");
                                String hours = String.valueOf(rs.getInt("hours"));
                                model.addRow(new Object[] { class_name, subject, faculty, hours });
                        }

                        rs.close();
                        stmt.close();
                        con.close();
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MapClasses.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MapClasses.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MapClasses.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MapClasses.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MapClasses().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JButton map_btn_delete;
        private javax.swing.JButton map_btn_map;
        private javax.swing.JComboBox<String> map_cmp_class;
        private javax.swing.JComboBox<String> map_cmp_faculty;
        private javax.swing.JComboBox<String> map_cmp_subject;
        private javax.swing.JTable map_table;
        private javax.swing.JTextField map_tf_hours;
        // End of variables declaration
}
