/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class SubjectScreen extends javax.swing.JFrame {

        /**
         * Creates new form SubjectScreen
         */
        public SubjectScreen() {
                initComponents();
                LoadSubjectCode();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                subject_tf_subjectname = new javax.swing.JTextField();
                subject_tf_subjectcode = new javax.swing.JTextField();
                subject_btn_addsubject = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                subject_table = new javax.swing.JTable();
                subject_btn_delete = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 153, 204));

                jPanel2.setBackground(new java.awt.Color(255, 153, 153));

                jPanel3.setBackground(new java.awt.Color(255, 153, 153));

                jLabel2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel2.setText("Subject Name");

                jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                jLabel3.setText("Subject Code");

                subject_btn_addsubject.setBackground(new java.awt.Color(255, 102, 255));
                subject_btn_addsubject
                                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add (1).png"))); // NOI18N
                subject_btn_addsubject.setText("Add Subject");
                subject_btn_addsubject.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                subject_btn_addsubjectActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(subject_btn_addsubject,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                250, Short.MAX_VALUE)
                                                                                .addComponent(subject_tf_subjectname)
                                                                                .addComponent(jLabel2,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel3,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(subject_tf_subjectcode))
                                                                .addContainerGap()));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(subject_tf_subjectname,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                33,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(25, 25, 25)
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(subject_tf_subjectcode,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                33,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(116, 116, 116)
                                                                .addComponent(subject_btn_addsubject,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                43,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(135, Short.MAX_VALUE)));

                jLabel1.setBackground(new java.awt.Color(255, 153, 153));
                jLabel1.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 0));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Subjects");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(43, 43, 43)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                jLabel4.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("Subject List");

                subject_table.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                subject_table.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Subject Name", "Subject Code"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.String.class, java.lang.Object.class
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(subject_table);

                subject_btn_delete.setBackground(new java.awt.Color(255, 102, 102));
                subject_btn_delete.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
                subject_btn_delete.setText("Delete Subject");
                subject_btn_delete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                subject_btn_deleteActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                .addGap(0, 540, Short.MAX_VALUE)
                                                                                                                .addComponent(subject_btn_delete,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                146,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                                .addContainerGap()));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                27,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(35, 35, 35)
                                                                .addComponent(subject_btn_delete,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                382,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>

        private void subject_btn_addsubjectActionPerformed(java.awt.event.ActionEvent evt) {
                String subject_name = subject_tf_subjectname.getText();
                String subject_code = subject_tf_subjectcode.getText();

                if (subject_name.isEmpty() || subject_code.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Please fill all the fields", "Try Again",
                                        JOptionPane.ERROR_MESSAGE);
                } else {
                        try {
                                // Database Connection
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                                "root", "aswin@2004");
                                String sql = "INSERT INTO subject (subject_name, subject_code) VALUES (?, ?)";
                                PreparedStatement pst = con.prepareStatement(sql);
                                pst.setString(1, subject_name);
                                pst.setString(2, subject_code);

                                int rowsInserted = pst.executeUpdate();
                                if (rowsInserted > 0) {
                                        JOptionPane.showMessageDialog(this, "Subject added successfully!");

                                        // Adding to table model
                                        DefaultTableModel model = (DefaultTableModel) subject_table.getModel();
                                        model.addRow(new Object[] { subject_name, subject_code });
                                }

                                // Close resources
                                pst.close();
                                con.close();
                        } catch (SQLException e) {
                                JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                }

                subject_tf_subjectname.setText("");
                subject_tf_subjectcode.setText("");
        }

        private void subject_btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = subject_table.getSelectedRow(); // Get selected row index

                if (selectedRow == -1) {
                        JOptionPane.showMessageDialog(this, "Please select a Subject to delete!", "Warning",
                                        JOptionPane.WARNING_MESSAGE);
                        return;
                }

                DefaultTableModel model = (DefaultTableModel) subject_table.getModel();
                String classCode = model.getValueAt(selectedRow, 1).toString(); // Assuming class_code is in column
                                                                                // index 1

                int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this subject?",
                                "Confirm Deletion", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                        try {
                                // Replace with your actual database connection details
                                Connection con = DriverManager.getConnection(
                                                "jdbc:mysql://localhost:3306/timesync", "root", "aswin@2004");
                                String query = "DELETE FROM subject WHERE subject_code = ?"; // Modify as needed
                                PreparedStatement pstmt = con.prepareStatement(query);
                                pstmt.setString(1, classCode);

                                int rowsAffected = pstmt.executeUpdate();
                                pstmt.close();
                                con.close();

                                if (rowsAffected > 0) {
                                        model.removeRow(selectedRow); // Remove row from table
                                        JOptionPane.showMessageDialog(this, "Subject deleted successfully!", "Success",
                                                        JOptionPane.INFORMATION_MESSAGE);
                                } else {
                                        JOptionPane.showMessageDialog(this, "Subject not found in database!", "Error",
                                                        JOptionPane.ERROR_MESSAGE);
                                }

                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(this, "Error deleting class: " + e.getMessage(), "Error",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                }
        }

        private void LoadSubjectCode() {
                DefaultTableModel model = (DefaultTableModel) subject_table.getModel();
                model.setRowCount(0); // Clear existing data

                try {
                        // Replace with your actual database connection details
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timesync",
                                        "root", "aswin@2004");
                        Statement stmt = con.createStatement();
                        String query = "SELECT subject_name, subject_code FROM subject"; // Modify according to your
                                                                                         // table
                        ResultSet rs = stmt.executeQuery(query);

                        while (rs.next()) {
                                String className = rs.getString("subject_name");
                                String classCode = rs.getString("subject_code");
                                model.addRow(new Object[] { className, classCode });
                        }

                        rs.close();
                        stmt.close();
                        con.close();
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(SubjectScreen.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(SubjectScreen.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(SubjectScreen.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(SubjectScreen.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new SubjectScreen().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JButton subject_btn_addsubject;
        private javax.swing.JButton subject_btn_delete;
        private javax.swing.JTable subject_table;
        private javax.swing.JTextField subject_tf_subjectcode;
        private javax.swing.JTextField subject_tf_subjectname;
        // End of variables declaration
}
